import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { FC, useMemo } from 'react';
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import { PhantomWalletAdapter, SolflareWalletAdapter } from '@solana/wallet-adapter-wallets';
import {
    WalletModalProvider,
    WalletDisconnectButton,
    WalletMultiButton
} from '@solana/wallet-adapter-react-ui';
import { clusterApiUrl } from '@solana/web3.js';
import HomeView from '../components/HomeView';

// Default styles that can be overridden by your app
require('@solana/wallet-adapter-react-ui/styles.css');

const Home: NextPage = () => {

  // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'.
  const network = WalletAdapterNetwork.Devnet;

  // You can also provide a custom RPC endpoint.
  const endpoint = useMemo(() => clusterApiUrl(network), [network]);

  const wallets = useMemo(
    () => [
        /**
         * Select the wallets you wish to support, by instantiating wallet adapters here.
         *
         * Common adapters can be found in the npm package `@solana/wallet-adapter-wallets`.
         * That package supports tree shaking and lazy loading -- only the wallets you import
         * will be compiled into your application, and only the dependencies of wallets that
         * your users connect to will be loaded.
         */
        new PhantomWalletAdapter(),
        new SolflareWalletAdapter(),
    ],
    []
);
  return (
    <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletModalProvider>
                    <WalletMultiButton />
                    <WalletDisconnectButton />
                    <div className={styles.container}>
                      <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                      </Head>

                      <HomeView />

                      <footer className={styles.footer}>
                        <a
                          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          Powered by{' '}
                          <span className={styles.logo}>
                            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                          </span>
                        </a>
                      </footer>
                    </div>
                </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
  )
}

export default Home
